name 'om-ogawa-env'
maintainer 'Peter Adkins'
maintainer_email 'pete@kernelpicnic.net'
description 'Installs/Configures an Ogawa node'
long_description 'Installs/Configures an Ogawa node'
version '0.4.0'

depends 'apt', '= 5.0.0'
depends 'ntp', '= 3.2.0'
depends 'java', '= 1.50.0'
depends 'sysctl', '= 0.8.0'
depends 'iptables', '= 4.3.1'
depends 'poise-python', '= 1.5.1'
depends 'elasticsearch', '= 3.0.1'
